import { DEFAULT_PILLARS } from '../pillars.js'
import type { PracticeDefinition } from '../types.js'

export const constructionPractice: PracticeDefinition = {
  id: 'construction',
  projectKind: 'construction',
  labelVi: 'TKDA & Giám sát thi công',
  labelEn: 'Design & site supervision',
  subtitleVi: 'Hạng mục · nhật ký GS · biên bản hiện trường',
  subtitleEn: 'Work packages · supervision logs · site minutes',
  titleFacetId: 'packageTitle',
  facets: [
    {
      id: 'projectName',
      labelVi: 'Công trình / dự án',
      labelEn: 'Project',
      required: true,
    },
    {
      id: 'phase',
      labelVi: 'Giai đoạn',
      labelEn: 'Phase',
      required: true,
      options: ['Thiết kế', 'Chào thầu', 'Thi công', 'Nghiệm thu', 'Bảo hành'],
    },
    {
      id: 'packageTitle',
      labelVi: 'Hạng mục / đợt GS',
      labelEn: 'Work package / visit',
      required: true,
    },
    {
      id: 'discipline',
      labelVi: 'Chuyên môn',
      labelEn: 'Discipline',
      options: ['Kiến trúc', 'Kết cấu', 'MEP', 'Hạ tầng', 'Tổng hợp'],
    },
  ],
  pillars: DEFAULT_PILLARS,
  materialRoles: [
    { id: 'nhat-ky-gs', labelVi: 'Nhật ký giám sát', labelEn: 'Supervision log', app: 'docs' },
    { id: 'bien-ban-ht', labelVi: 'Biên bản hiện trường', labelEn: 'Site minutes', app: 'docs' },
    { id: 'checklist-gs', labelVi: 'Checklist GS', labelEn: 'Supervision checklist', app: 'sheets' },
    { id: 'bao-cao-tuan', labelVi: 'Báo cáo tuần', labelEn: 'Weekly report', app: 'docs' },
    { id: 'slide-hop', labelVi: 'Slide họp dự án', labelEn: 'Project meeting slides', app: 'slides' },
    { id: 'khac', labelVi: 'Khác', labelEn: 'Other', app: 'docs' },
  ],
  templates: [
    {
      id: 'nhat-ky-gs',
      labelVi: 'Nhật ký GS',
      labelEn: 'Supervision log',
      app: 'docs',
      materialRole: 'nhat-ky-gs',
    },
    {
      id: 'bien-ban-ht',
      labelVi: 'Biên bản HT',
      labelEn: 'Site minutes',
      app: 'docs',
      materialRole: 'bien-ban-ht',
    },
    {
      id: 'bao-cao-tuan',
      labelVi: 'Báo cáo tuần',
      labelEn: 'Weekly report',
      app: 'docs',
      materialRole: 'bao-cao-tuan',
    },
  ],
  skills: [
    {
      id: 'nhat-ky-hom-nay',
      category: 'giam-sat',
      labelVi: 'Nhật ký GS trong ngày',
      labelEn: 'Daily supervision log',
      descVi: 'Khung nhật ký: thời tiết, nhân lực, khối lượng, tồn đọng.',
      descEn: 'Log frame: weather, crew, quantities, issues.',
      app: 'docs',
      seedRole: 'nhat-ky-gs',
      usesAi: true,
    },
    {
      id: 'checklist-nghiem-thu',
      category: 'nghiem-thu',
      labelVi: 'Checklist nghiệm thu hạng mục',
      labelEn: 'Handover checklist',
      descVi: 'Danh mục kiểm tra theo giai đoạn.',
      descEn: 'Inspection items by phase.',
      app: 'docs',
      seedRole: 'checklist-gs',
      usesAi: true,
    },
    {
      id: 'bao-cao-tuan-ai',
      category: 'bao-cao',
      labelVi: 'Nháp báo cáo tuần',
      labelEn: 'Weekly report draft',
      descVi: 'Tiến độ, rủi ro, đề xuất tuần tới.',
      descEn: 'Progress, risks, next-week asks.',
      app: 'docs',
      seedRole: 'bao-cao-tuan',
      usesAi: true,
    },
  ],
  freeChainTemplateIds: ['nhat-ky-gs', 'bien-ban-ht', 'bao-cao-tuan'],
}
