import { DEFAULT_PILLARS } from '../pillars.js'
import type { PracticeDefinition } from '../types.js'

export const legalPractice: PracticeDefinition = {
  id: 'legal',
  projectKind: 'legal',
  labelVi: 'Luật sư / Pháp lý',
  labelEn: 'Legal counsel',
  subtitleVi: 'Hồ sơ vụ việc · hợp đồng · biên bản trên máy',
  subtitleEn: 'Matters · contracts · minutes on device',
  titleFacetId: 'matterTitle',
  facets: [
    {
      id: 'client',
      labelVi: 'Khách hàng / bên',
      labelEn: 'Client / party',
      required: true,
      placeholderVi: 'VD: Công ty ABC',
      placeholderEn: 'e.g. ABC Co.',
    },
    {
      id: 'matterType',
      labelVi: 'Loại việc',
      labelEn: 'Matter type',
      required: true,
      options: ['Hợp đồng', 'Tranh chấp', 'Tư vấn', 'Tuân thủ', 'Sở hữu trí tuệ', 'Khác'],
    },
    {
      id: 'matterTitle',
      labelVi: 'Tên vụ / hồ sơ',
      labelEn: 'Matter title',
      required: true,
    },
    {
      id: 'jurisdiction',
      labelVi: 'Thẩm quyền',
      labelEn: 'Jurisdiction',
      options: ['Việt Nam', 'Quốc tế', 'Khác'],
    },
  ],
  pillars: DEFAULT_PILLARS,
  materialRoles: [
    { id: 'hop-dong', labelVi: 'Hợp đồng', labelEn: 'Contract', app: 'docs' },
    { id: 'cong-van', labelVi: 'Công văn / thư', labelEn: 'Letter', app: 'docs' },
    { id: 'bien-ban', labelVi: 'Biên bản', labelEn: 'Minutes', app: 'docs' },
    { id: 'tom-tat-vu', labelVi: 'Tóm tắt vụ', labelEn: 'Case brief', app: 'docs' },
    { id: 'checklist', labelVi: 'Checklist tuân thủ', labelEn: 'Compliance checklist', app: 'sheets' },
    { id: 'khac', labelVi: 'Khác', labelEn: 'Other', app: 'docs' },
  ],
  templates: [
    { id: 'hop-dong', labelVi: 'Khung hợp đồng', labelEn: 'Contract outline', app: 'docs', materialRole: 'hop-dong' },
    { id: 'tom-tat-vu', labelVi: 'Tóm tắt vụ', labelEn: 'Case brief', app: 'docs', materialRole: 'tom-tat-vu' },
    { id: 'bien-ban', labelVi: 'Biên bản', labelEn: 'Minutes', app: 'docs', materialRole: 'bien-ban' },
  ],
  skills: [
    {
      id: 'ra-soat-hd',
      category: 'hop-dong',
      labelVi: 'Rà soát điều khoản HĐ',
      labelEn: 'Contract clause review',
      descVi: 'Gợi ý rủi ro / thiếu sót điều khoản chính.',
      descEn: 'Flag key clause risks / gaps.',
      app: 'docs',
      seedRole: 'hop-dong',
      usesAi: true,
    },
    {
      id: 'tom-tat-ho-so',
      category: 'vu-viec',
      labelVi: 'Tóm tắt hồ sơ',
      labelEn: 'Matter summary',
      descVi: 'Tóm tắt sự kiện, yêu cầu, điểm pháp lý.',
      descEn: 'Summarize facts, asks, legal points.',
      app: 'docs',
      seedRole: 'tom-tat-vu',
      usesAi: true,
    },
    {
      id: 'thu-yeu-cau',
      category: 'thu-tin',
      labelVi: 'Nháp thư yêu cầu',
      labelEn: 'Demand letter draft',
      descVi: 'Nháp thư lịch sự, nêu căn cứ và yêu cầu.',
      descEn: 'Polite demand letter with grounds.',
      app: 'docs',
      seedRole: 'cong-van',
      usesAi: true,
    },
  ],
  freeChainTemplateIds: ['tom-tat-vu', 'hop-dong', 'bien-ban'],
}
