import { DEFAULT_PILLARS } from '../pillars.js'
import type { PracticeDefinition } from '../types.js'

export const principalPractice: PracticeDefinition = {
  id: 'principal',
  projectKind: 'principal',
  labelVi: 'Hiệu trưởng',
  labelEn: 'School principal',
  subtitleVi: 'Kế hoạch nhà trường · báo cáo · chỉ đạo chuyên môn',
  subtitleEn: 'School plans · reports · academic leadership',
  titleFacetId: 'planTitle',
  facets: [
    {
      id: 'school',
      labelVi: 'Trường',
      labelEn: 'School',
      required: true,
    },
    {
      id: 'schoolYear',
      labelVi: 'Năm học',
      labelEn: 'School year',
      required: true,
      placeholderVi: 'VD: 2025–2026',
      placeholderEn: 'e.g. 2025–2026',
    },
    {
      id: 'planTitle',
      labelVi: 'Tên kế hoạch / báo cáo',
      labelEn: 'Plan / report title',
      required: true,
    },
    {
      id: 'scope',
      labelVi: 'Phạm vi',
      labelEn: 'Scope',
      options: ['Toàn trường', 'Tổ chuyên môn', 'Khối', 'Hoạt động ngoài giờ'],
    },
  ],
  pillars: DEFAULT_PILLARS,
  materialRoles: [
    { id: 'ke-hoach-nam', labelVi: 'Kế hoạch năm', labelEn: 'Annual plan', app: 'docs' },
    { id: 'bao-cao-thang', labelVi: 'Báo cáo tháng', labelEn: 'Monthly report', app: 'docs' },
    { id: 'chi-dao', labelVi: 'Công văn chỉ đạo', labelEn: 'Directive', app: 'docs' },
    { id: 'lich-hop', labelVi: 'Lịch / biên bản họp', labelEn: 'Meeting agenda/minutes', app: 'docs' },
    { id: 'slide-hop-phu-huynh', labelVi: 'Slide họp PH', labelEn: 'Parent meeting slides', app: 'slides' },
    { id: 'khac', labelVi: 'Khác', labelEn: 'Other', app: 'docs' },
  ],
  templates: [
    {
      id: 'ke-hoach-nam',
      labelVi: 'Kế hoạch năm',
      labelEn: 'Annual plan',
      app: 'docs',
      materialRole: 'ke-hoach-nam',
    },
    {
      id: 'bao-cao-thang',
      labelVi: 'Báo cáo tháng',
      labelEn: 'Monthly report',
      app: 'docs',
      materialRole: 'bao-cao-thang',
    },
    {
      id: 'lich-hop',
      labelVi: 'Biên bản họp',
      labelEn: 'Meeting minutes',
      app: 'docs',
      materialRole: 'lich-hop',
    },
  ],
  skills: [
    {
      id: 'ke-hoach-nam-ai',
      category: 'ke-hoach',
      labelVi: 'Khung kế hoạch năm học',
      labelEn: 'Annual plan outline',
      descVi: 'Mục tiêu, nhiệm vụ theo tháng, chỉ số theo dõi.',
      descEn: 'Goals, monthly tasks, tracking metrics.',
      app: 'docs',
      seedRole: 'ke-hoach-nam',
      usesAi: true,
    },
    {
      id: 'bao-cao-thang-ai',
      category: 'bao-cao',
      labelVi: 'Nháp báo cáo tháng',
      labelEn: 'Monthly report draft',
      descVi: 'Kết quả, tồn tại, việc tuần/tháng tới.',
      descEn: 'Results, gaps, next actions.',
      app: 'docs',
      seedRole: 'bao-cao-thang',
      usesAi: true,
    },
    {
      id: 'thong-diep-phu-huynh',
      category: 'truyen-thong',
      labelVi: 'Thông điệp họp phụ huynh',
      labelEn: 'Parent meeting message',
      descVi: 'Dàn ý slide/nói chuyện ngắn, tích cực.',
      descEn: 'Short positive talking points / slides.',
      app: 'slides',
      seedRole: 'slide-hop-phu-huynh',
      usesAi: true,
    },
  ],
  freeChainTemplateIds: ['ke-hoach-nam', 'bao-cao-thang', 'lich-hop'],
}
