import { DEFAULT_PILLARS } from '../pillars.js'
import type { PracticeDefinition } from '../types.js'

export const procurementPractice: PracticeDefinition = {
  id: 'procurement',
  projectKind: 'procurement',
  labelVi: 'Đầu tư / Mua sắm',
  labelEn: 'Investment / procurement',
  subtitleVi: 'Gói thầu · RFQ · so sánh báo giá trên máy',
  subtitleEn: 'Tenders · RFQ · quote comparison on device',
  titleFacetId: 'packageTitle',
  facets: [
    {
      id: 'org',
      labelVi: 'Đơn vị',
      labelEn: 'Organization',
      required: true,
    },
    {
      id: 'category',
      labelVi: 'Nhóm hàng / dịch vụ',
      labelEn: 'Category',
      required: true,
      options: ['Hàng hóa', 'Dịch vụ', 'Xây lắp', 'Tư vấn', 'CNTT', 'Khác'],
    },
    {
      id: 'packageTitle',
      labelVi: 'Tên gói',
      labelEn: 'Package title',
      required: true,
    },
    {
      id: 'method',
      labelVi: 'Hình thức',
      labelEn: 'Method',
      options: ['Chào hàng cạnh tranh', 'Chỉ định', 'Đấu thầu rộng rãi', 'Mua sắm thường xuyên'],
    },
  ],
  pillars: DEFAULT_PILLARS,
  materialRoles: [
    { id: 'to-trinh', labelVi: 'Tờ trình nhu cầu', labelEn: 'Need memo', app: 'docs' },
    { id: 'rfq', labelVi: 'RFQ / Yêu cầu báo giá', labelEn: 'RFQ', app: 'docs' },
    { id: 'bang-so-sanh', labelVi: 'Bảng so sánh giá', labelEn: 'Quote comparison', app: 'sheets' },
    { id: 'bien-ban-chon', labelVi: 'Biên bản chọn nhà cung cấp', labelEn: 'Award minutes', app: 'docs' },
    { id: 'hop-dong-ms', labelVi: 'Hợp đồng mua sắm', labelEn: 'Purchase contract', app: 'docs' },
    { id: 'khac', labelVi: 'Khác', labelEn: 'Other', app: 'docs' },
  ],
  templates: [
    { id: 'to-trinh', labelVi: 'Tờ trình', labelEn: 'Need memo', app: 'docs', materialRole: 'to-trinh' },
    { id: 'rfq', labelVi: 'RFQ', labelEn: 'RFQ', app: 'docs', materialRole: 'rfq' },
    {
      id: 'bien-ban-chon',
      labelVi: 'BB chọn NCC',
      labelEn: 'Award minutes',
      app: 'docs',
      materialRole: 'bien-ban-chon',
    },
  ],
  skills: [
    {
      id: 'nhap-rfq',
      category: 'chao-gia',
      labelVi: 'Nháp RFQ',
      labelEn: 'Draft RFQ',
      descVi: 'Phạm vi, tiêu chí, thời hạn, yêu cầu hồ sơ.',
      descEn: 'Scope, criteria, deadlines, submission asks.',
      app: 'docs',
      seedRole: 'rfq',
      usesAi: true,
    },
    {
      id: 'tieu-chi-danh-gia',
      category: 'danh-gia',
      labelVi: 'Tiêu chí đánh giá NCC',
      labelEn: 'Vendor scorecard',
      descVi: 'Bảng tiêu chí điểm + trọng số gợi ý.',
      descEn: 'Suggested scored criteria + weights.',
      app: 'docs',
      seedRole: 'bang-so-sanh',
      usesAi: true,
    },
    {
      id: 'to-trinh-ms',
      category: 'to-trinh',
      labelVi: 'Nháp tờ trình mua sắm',
      labelEn: 'Procurement memo',
      descVi: 'Căn cứ nhu cầu, dự toán, đề xuất hình thức.',
      descEn: 'Need, estimate, recommended method.',
      app: 'docs',
      seedRole: 'to-trinh',
      usesAi: true,
    },
  ],
  freeChainTemplateIds: ['to-trinh', 'rfq', 'bien-ban-chon'],
}
